name: weaviate
description: The Weaviate Dart project provides a Dart wrapper for the Weaviate REST API, enabling developers to interact with a Weaviate vector database.
version: 1.0.0
homepage: https://github.com/faithoflifedev/weaviate-dart
repository: https://github.com/faithoflifedev/weaviate-dart.git

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dio: ^5.2.1+1
  graphql: ^5.1.3
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  retrofit: ^4.0.1
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.5
  grinder: ^0.9.4
  json_serializable: ^6.7.0
  lints: ^4.0.0
  publish_tools: ^1.0.0+4
  retrofit_generator: ^8.1.0
  test: ^1.24.3
