/// app metadata
library meta;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"weaviate","version":"1.26.4","homepage":"https://github.com/faithoflifedev/weaviate-dart","environment":{"sdk":">=3.2.0 <4.0.0"},"description":"The Weaviate Dart project provides a Dart wrapper for the Weaviate REST API, enabling developers to interact with a Weaviate vector database.","dependencies":{"args":"^2.5.0","dio":"^5.7.0","graphql":"^5.1.3","json_annotation":"^4.9.0","loggy":"^2.0.3","retrofit":"^4.1.1","universal_io":"^2.2.2"},"dev_dependencies":{"build_runner":"^2.4.12","grinder":"^0.9.5","json_serializable":"^6.8.0","lints":"^5.0.0","publish_tools":"^1.0.0+4","retrofit_generator":"^9.1.2","test":"^1.25.8"},"repository":"https://github.com/faithoflifedev/weaviate-dart.git","funding":["https://www.buymeacoffee.com/faithoflif2"]}');
